#!/usr/bin/env python
# coding: utf-8

"""visualizer script by Yasushi Masuda (ymasuda@accense.com)

usage: visualizer [-h] [-D]

optional arguments:
  -h, --help  show this help message and exit
  -D          debug mode

"""

import sys
from argparse import ArgumentParser
from logging import basicConfig, debug, getLogger, DEBUG

from ec4vis.app import BrowserApp


basicConfig()


def main(args=()):
    args_parser = ArgumentParser()
    args_parser.add_argument('-D', help='debug mode', action='store_true', dest='debug')
    parsed_arguments = args_parser.parse_args(args)
    if parsed_arguments.debug:
        getLogger().setLevel(DEBUG)
        debug('Entered DEBUG mode.\n')
    app = BrowserApp(0)
    if app:
        try:
            app.MainLoop()
        except Exception, e:
            debug('Exiting on exception %s: %s' %(str(type(e).__name__), str(e)))
    else:
        wx.SafeShowMessage(
            'Confused...',
            'Unable to initialize application instance. Aborting.')


if __name__=='__main__':
    main(args=sys.argv[1:])
